feat: allow to select sdk with .sdk_name
cartesi/cli pull request #27
Opened 2024-05-13 13:07 UTC by stskeeps

2024-05-13 15:45 UTC, endersonmaia requested changes

2024-05-13 15:45 UTC, endersonmaia commented on apps/cli/src/commands/build.ts
> +const CARTESI_DEFAULT_SDK_VERSION = "0.7.0";
Since the PR #26  suggests a patch to cartesi/sdk, this should be:

```suggestion
const CARTESI_DEFAULT_SDK_VERSION = "0.6.2";
```

2024-05-15 09:43 UTC, stskeeps commented
This should now in shape, opinions?

2024-05-15 13:24 UTC, tuler approved these changes

2024-05-15 14:15 UTC, tuler commented
I tested with rollups and it works as it should. Applications will need to upgrade the SDK version 0.6.0 to 0.6.2, as we are setting the minimum required version to 0.6.2.

2024-05-15 17:08 UTC, endersonmaia approved these changes

2024-05-15 17:09 UTC, merged